### ISSUE TITLE
Make sure that the screens will look the same on every device

### ISSUE THREAD

**Issue by Tamir198** [CyBear-Jinni/CBJ_App#119]
I want to help with this project and make sure that all the screens will look the same on all devices. 

Basically, I want to replace all the fixed size values in the project (for example `radius: 48.0`) with something more dynamic.
The current fixed size for the widgets and spaces between them may look good on one device but it may not look so good on another device because different phones got different screen sizes.

How do I want to do it
-

In order to determine the screen dimensions, I want to use the `MediaQuery` class [https://stackoverflow.com/questions/49553402/flutter-screen-size](https://stackoverflow.com/questions/49553402/flutter-screen-size).

` final Size screenSize = MediaQuery.of(context).size;`

A problem
-

I need to get access to context, this is fine in Stateful Widgets when I have the state object, but when I am having a Stateless Widget I can not access cotext.

For more info check [https://github.com/flutter/flutter/issues/23400](https://github.com/flutter/flutter/issues/23400)

Solution
-

I can either pass context as an argument via the class constructor or I can convert the class to Stateful Widget.
I think that the better approach will be to pass it via constructor argument, because if some screen data will not change there is no point in using a Stateful Widget.

---

What approach would you like me to take?
If there is a better one I am willing to take it.

**Comment by guyluz11** [comment]
So first of all I understand that you want this issue so I will assignee it to you @Tamir198, 

Using `Stateful Widget` all the time will be waste of resources so we will go with the first option.

Using `context` inside a `Stateless Widget` can be done and there are even places we do it already in the app.
![image](https://user-images.githubusercontent.com/9304740/101268201-2e21e880-3769-11eb-97bc-c178345f3a0e.png)

If you use the size of the screen and don't have context you can also store it in a singleton as it will be used a lot during the app.

But please check again about the `Stateless Widget` before doing so because this is the best way to use it.

**Comment by guyluz11** [comment]
Thanks for the pull request, 
Closing as it was merged
