### ISSUE TITLE
hello sir , i want to know what the steps to control smart lamp remotly using flutter 

### ISSUE THREAD

**Issue by ahkamkhalaf** [CyBear-Jinni/cbj_app#296]

**Comment by guyluz11** [comment]
Hi @ahkamkhalaf how are you.

Currently you can control the supported devices only in the local network, we are working on adding support to control outside of the home too.

First you need to check if your device vendor is supported, we currently support Yeelight, Switcher, ESPHome, Tasmota and we are working on more.
If your vendor does not exist you can ask us to add support for it with GitHub issue in our [CyBear Jinni Hub](https://github.com/CyBear-Jinni/cbj_hub) repo or to tell us in our [Discord server](https://discord.gg/mUXfwUY).

You can check the steps to set up in our site [cybearjinni](https://cybearjinni.com/#/) in the "Set Up" section
But basically these are the steps:

1. Install the hub on Linux computer 
    * Install this program [mosquitto](https://snapcraft.io/mosquitto).
    * And Install this program [cbj-hub](https://snapcraft.io/cbj-hub).

2. Install the app to control the hub
    * [Android play store link](https://play.google.com/store/apps/details?id=com.cybear_jinni.smart_home)

If you want there is a voice chat in our Discord server so that you can talk with someone if it is easier for you


[<img src="https://cdn.icon-icons.com/icons2/2108/PNG/512/discord_icon_130958.png" height="80">](https://discord.gg/mUXfwUY)

**Comment by guyluz11** [comment]
That sounds like a question for programming forums, this github repo is **dedicated** for CyBear Jinni.

But in general it depends on a lot of staff.
Most of the time you have A smarter device that sits in the middle like a hub and it is talking to the google cloud.

With a quick google search I have found this [Can Arduino Uno send data to Cloud Firestore?](https://stackoverflow.com/questions/56430487/can-arduino-uno-send-data-to-cloud-firestore), and this one [Using Firebase to control your Arduino project over the web](https://medium.com/firebase-developers/using-firebase-to-control-your-arduino-project-over-the-web-ba94569d172c).

If you want to use Arduino you can even take parts from [here](https://github.com/guyluz11/Smart-Power-Outlet/blob/master/microcontroller%20code/microcontroller_code/microcontroller_code.ino), but I didn't have time to add the firebase (google cloud) part.

**Comment by guyluz11** [comment]
Will close this issue as it is not relevant to CyBear Jinni
