### ISSUE TITLE
Add support for esphome

### ISSUE THREAD

**Issue by charithmadhuranga** [CyBear-Jinni/cbj_app#396]
Considering tasmota is already supported why not add esphome.....it will be a huge influence to people already using home assistant to have a look at this app as a alternative.

**Comment by guyluz11** [comment]
Indeed, support for ESPHome could boost this projects.

Unfortunately there is no ESPHome package for dart in the pub.dev and building implementation in dart can take time.

I have actually started the work on adding support in the hub repo 

https://github.com/CyBear-Jinni/cbj_hub/issues/10

But never completed the implementation, so currently it's waiting for someone to pick it up.

This project support Hacktoberfest so in the spirit of the open source holiday pr are welcome, if you need any help I will be more than happy to help in here or in the discord server 😁.

**Comment by guyluz11** [comment]
@charithmadhuranga I have a question for you.
Does having support for ESPHome web server good enough?

I found out that if people add to the ESPHome configuration file (`.yaml`) the following part

```
web_server:
	port:80
```

which adds a web server it will be easier to create a code for cbj to interact with it.

I worry that most people do not use that and will think cbj just can't find their supported devices since there is a way to do the same without that line.

What do you think?

**Comment by piyushkumar12111111** [comment]
Assign this to me

**Comment by guyluz11** [comment]
@piyushkumar12111111 ESPHome is running on Arduino.

Do you have Arduino with ESPHome installed?
If so please comment here https://github.com/CyBear-Jinni/cbj_hub/issues/10, adding ESPHome support should come from the cbj hub and not the app. 

For any help about it you can ask in the cbj discord server 
<a href="https://discord.gg/mUXfwUY">
<img align="left" alt="Discord" width="45px" src="https://cdn.icon-icons.com/icons2/2108/PNG/512/discord_icon_130958.png" /></a>

**Comment by guyluz11** [comment]
We have just completed basic support for ESPHome.

Currently suggest support identity but it is pretty easy to add more.

I am going to push an update to the snap store that include the support in the coming hours.

Thanks
